version: '3.1'

services:

  db:
    image: postgres:13
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./data:/data/postgres
      - ./backup:/backup
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres