---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 84.201.172.141
    jenkins-agent-01:
      ansible_host: 130.193.50.72
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: bansh