version: '3.1'

services:

  db:
    image: postgres:12.8
    restart: unless-stopped
    volumes:
      - ./data:/data/postgres
      - ./backup:/backup
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080