apiVersion: apps/v1   
kind: Deployment   
metadata:   
  labels:   
    app: front   
  name: frontend   
  namespace: default  
spec:   
  replicas: 1   
  selector:   
    matchLabels:   
      app: front   
  template:   
    metadata:   
      labels:   
        app: front   
    spec:   
      containers:   
      - image: nginx:1.20   
        imagePullPolicy: IfNotPresent   
        name: frontend   
        env:
          - name: HTTP_PORT
            value: "8000"      
          - name: backend
            value: "9000"
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
