all:
  hosts:
    master1:
      ansible_host: 51.250.14.16
      ansible_user: yc-user
    master2:
      ansible_host: 51.250.86.233
      ansible_user: yc-user
  children:
    kube_control_plane:
      hosts:
        master1:
        master2:
    kube_node:
      hosts:
        master1:
        master2:
    etcd:
      hosts:
        master1:
        master2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
