apiVersion: apps/v1   
kind: Deployment   
metadata:   
  labels:   
    app: frontback   
  name: front-back   
  namespace: default  
spec:   
  replicas: 1   
  selector:   
    matchLabels:   
      app: frontback   
  template:   
    metadata:   
      labels:   
        app: frontback   
    spec:
      containers:   
      - image: nginx:1.20   
        imagePullPolicy: IfNotPresent   
        name: frontend   
      - image: praqma/network-multitool:alpine-extra   
        imagePullPolicy: IfNotPresent   
        name: backend   
        env:   
          - name: HTTP_PORT   
            value: "8080"      

---
apiVersion: v1
kind: Service
metadata:
  name: front-back
  namespace: default
spec:
  ports:
    - name: web
      port: 8080
  selector:
    app: frontback
  type: ClusterIP