apiVersion: apps/v1   
kind: Deployment   
metadata:   
  labels:   
    app: back   
  name: backend   
  namespace: default  
spec:   
  replicas: 3   
  selector:   
    matchLabels:   
      app: back   
  template:   
    metadata:   
      labels:   
        app: back   
    spec:
      containers:   
      - image: praqma/network-multitool:alpine-extra   
        imagePullPolicy: IfNotPresent   
        name: backend   
        env:   
          - name: HTTP_PORT   
            value: "8080"
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /tmp/share
            name: share
      volumes:
      - name: share
        persistentVolumeClaim:
          claimName: nfs-pvc