apiVersion: apps/v1   
kind: Deployment   
metadata:   
  labels:   
    app: front   
  name: frontend   
  namespace: default  
spec:   
  replicas: 3   
  selector:   
    matchLabels:   
      app: front   
  template:   
    metadata:   
      labels:   
        app: front   
    spec:
      containers:   
      - image: nginx:1.20   
        imagePullPolicy: IfNotPresent   
        name: frontend
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /var/www
            name: share
      volumes:
      - name: share
        persistentVolumeClaim:
          claimName: nfs-pvc