---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: readonly
  name: developer-roles
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-role
  namespace: readonly
subjects:
- kind: User
  name: readonly
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-roles
  apiGroup: rbac.authorization.k8s.io